#!/usr/bin/env zsh

THISFILE=${0}
THISDIR=${0:A:h}
LC_NUMERIC=C # Make sure printf uses '.' in floating-point numbers

DB="collection.vizn"

errln() {
  echo "\033[31;1m[ERR ]\033[0m $@"
}

logln() {
  echo "\033[32;1m[INFO]\033[0m $@"
}

card() {
  if [ ! "$#" -eq 0 ]; then
    card_"$@"
  else
    card_usage
  fi
}

card_create() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$1" = "-?" ]; then
    card_create__usage
  elif [ ! "$#" -eq 0 ]; then
    [ "$2" = "" ] && info="NULL" || info="$2"
    id=$(date '+%s')
    reply=$(sqlite3 "$DB" "insert into cards(id, action, info) values("$id", '$1', '$info');" 2>&1)
    if [ ! "$?" -eq 0 ]; then
      errln "$reply"
      exit 1
    fi
    logln "Created new card with the following data:"
    logln "  - id     : $id"
    logln "  - action : $1"
    logln "  - info   : $info"
  else
    card_create_usage
  fi
}

card_create__usage() {
  echo "\
Usage:
  (1) $THISFILE $(echo $funcstack[1] | sed 's/__usage$//g' | tr '_' ' ') ACTION [INFO]"
}

card_view() {
  if [ ! "$#" -eq 0 ]; then
    reply=$(sqlite3 "$DB" "select action from cards where id==$1;" 2>&1)
    if [ "$?" -eq 0 ]; then
      logln "Viewing card '$1'."
      eval "$reply"
    else
      errln "No card matches id '$1'. Nothing done."
      exit 1
    fi
  fi
}

card_usage() {
  echo "card_usage: TODO"
}

collection() {
  if [ ! "$#" -eq 0 ]; then
    collection_"$@"
  else
    collection_usage
  fi
}

collection_create() {
  if [ -e "$1" ] || [ -z "$1" ]; then
    errln "File '$1' already exists or filename is empty. Nothing done."
    exit 1
  else
    sqlite3 "$1" 'create table cards(id integer primary key, action text not null, info text);'
    sqlite3 "$1" 'create table schedule(id integer primary key, duesec integer, duesecprev integer, numrevs);'
    logln "Created new collection '$1'."
  fi
}

collection_usage() {
  echo "collection_usage: TODO"
}

schedule() {
  if [ ! "$#" -eq 0 ]; then
    schedule_"$@"
  else
    schedule_usage
  fi
}

schedule_fsmeval() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$1" = "-?" ]; then
    schedule_fsmeval__usage 
  elif [ "$#" -eq 3 ]; then
    # TODO: Boundary checks
    T="$1";e="$2";q="$3";
    case $T in
      0)
        if [ "$q" -ge 0 ] && [ "$q" -le 3 ]; then
          T=60
        else
          T=600
        fi
        ;;
      60)
        if [ "$q" -ge 0 ] && [ "$q" -le 3 ]; then
          T=60
        else
          T=600
        fi
        ;;
      86400)
        if [ "$q" -eq 4 ] || [ "$q" -eq 5 ]; then
          T=518400
        elif [ "$q" -eq 3 ]; then
          T=86400
        else
          T=600
        fi
        ;;
      *)
        if [ "$q" -ge 3 ] && [ "$q" -le 5 ]; then
          T=$(printf '%d' $(( T*e )))
        else
          T=600
        fi
        del=$(printf '%.1f' $(( 0.1 * (q-4) )) )
        e=$(printf '%.1f' $(( e+del >= 1.3 ? e+del : 1.3 )) )
        ;;
    esac
    echo "{\"T\": $T, \"ε\": $e}"
  fi
}

schedule_fsmeval__usage() {
  echo "\
Usage:
  (1) $THISFILE $(echo $funcstack[1] | sed 's/__usage$//g' | tr '_' ' ') <T> <ε> <q>

Computes the next iteration of scheduling parameters based on the previous
interval 'T', the previous easyness factor 'ε' and the user's experienced
difficulty 'q'. Updated values are returned as json-formatted string."
}

schedule_update() {
  echo "schedule_update: TODO"
}

usage() {
  echo "TODO"
}

if [ ! "$#" = "0" ]; then
  "$@"
else
  usage
fi
