GET http://localhost:4004/cards/Cards

###

GET http://localhost:4004/cards/Schedules

###

POST http://localhost:4004/cards/Cards
Content-Type: application/json

{ "command" : "echo asdf" }
# Cannot read property 'ref' of undefined

###

GET http://localhost:4004/debug/srvtime() HTTP/1.1

###

GET http://localhost:4004/debug/foo() HTTP/1.1
